name: Example - App Build Flow

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  build-flow:
    uses: wgtechlabs/build-flow-action/.github/workflows/app.yml@v1
    secrets: inherit
    with:
      enable-package: true
      enable-container: true
      enable-release: true
      enable-codeql: false
      main-branch: main
      dev-branch: dev
