name: Example - Container Build Flow

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  container-flow:
    uses: wgtechlabs/build-flow-action/.github/workflows/container.yml@v1
    secrets: inherit
    with:
      enable-release: true
      main-branch: main
