name: Example - Package Build Flow

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  package-flow:
    uses: wgtechlabs/build-flow-action/.github/workflows/package.yml@v1
    secrets: inherit
    with:
      enable-release: true
      main-branch: main
