name: Example - Package Build Flow

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  package-flow:
    uses: wgtechlabs/build-flow-action/.github/workflows/package.yml@main
    secrets: inherit
    with:
      enable-release: ${{ github.ref == 'refs/heads/main' }}
      enable-gitleaks: true
      enable-codeql: true
      ci-profile: python
      ci-matrix-versions: '["3.11","3.12"]'
      ci-install-command: pip install -r requirements.txt
      ci-test-command: pytest -q
      main-branch: main
      dev-branch: dev
      publish-dev-artifacts: false
      publish-pr-artifacts: false
      publish-manual-artifacts: false
      package-registry: both
      package-dry-run: false
      release-changelog-path: ./CHANGELOG.md
      release-draft: false
      release-prerelease: false
      release-dry-run: false
      release-version-prefix: v
      release-create: true
